//
// Created by Brayan Cruz on 5/17/2024.
//

#ifndef DOUBLELINKEDLISTS_ECOUNTRY_H
#define DOUBLELINKEDLISTS_ECOUNTRY_H

enum class ECountry{
    ENGLAND, ITALY, FRANCE, GERMANY, NETHERLANDS, SPAIN, PORTUGAL, TÜRKEY, NO_SELECTED
};
#endif //DOUBLELINKEDLISTS_ECOUNTRY_H
