//
// Created by Brayan Cruz on 5/15/2024.
//

#ifndef DOUBLELINKEDLISTS_ELIGUE_H
#define DOUBLELINKEDLISTS_ELIGUE_H


enum class ELigue {
    PREMIER_LEAGUE, SERIE_A, BUNDESLIGA, LA_LIGA, LIGUE_1,EREDIVISIE,PRIMEIRA_LIGA, SÜPER_LIG
};

#endif //DOUBLELINKEDLISTS_ELIGUE_H
